version: '2'
services:
  bot:
    build: .
    restart: always
    ports:
      - 80:4000
      - 443:4000
      - 4000:4000
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - LOG__LEVEL=info
      - LOG__DIR=logs
      - LOG__EXCEPTIONS=true
      - NODE_ENV=production
      - PORT=4000
      - URL
      - TELEGRAM__TOKEN
      - TELEGRAM__USERNAME
      - TELEGRAM__SECRET_PATH
      - DONATIONS__BTC
      - DONATIONS__ETH
      - DONATIONS__DASH
      - DONATIONS__BCH
      - DONATIONS__LTC
      - DONATIONS__CHA
      - DONATIONS__ADA
